NDefines_Graphics = {
	NGraphics = {
	COUNTRY_FLAG_TEX_WIDTH = 82, -- Expected texture size
	COUNTRY_FLAG_TEX_HEIGHT = 52,
	COUNTRY_FLAG_MEDIUM_TEX_WIDTH = 41,
	COUNTRY_FLAG_MEDIUM_TEX_HEIGHT = 26,
	COUNTRY_FLAG_SMALL_TEX_WIDTH = 10,
	COUNTRY_FLAG_SMALL_TEX_HEIGHT = 7,
	COUNTRY_FLAG_TEX_MAX_SIZE = 512, -- Tweak dependly on amount of countries. Must be power of 2. No more then 2048.
	COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 128, -- Tweak dependly on amount of countries. Must be power of 2. No more then 2048.
	COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10,
	COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 4096,
	COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41,
	COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 8192,
	}
}